# Generated by Django 5.1.3 on 2024-12-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_list', '0007_directer_moviedata_directer_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='moviedata',
            name='acters',
            field=models.ManyToManyField(related_name='acted_movies', to='Movie_list.actor'),
        ),
    ]
